### ISSUE TITLE
Control elb_application_lb_waf_enabled providing incorrect result

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe-mod-aws-perimeter#11]
**Describe the bug**
Perimeter Mod is flagging it as disabled even though WAF is enabled for an ELB.

Slack reference - https://steampipe.slack.com/archives/C01UECB59A7/p1657569823027209

**Steampipe version (`steampipe -v`)**
Example: v0.15.0

**Plugin version (`steampipe plugin list`)**
Example: v0.68.0

**To reproduce**
steampipe check aws_perimeter.control.elb_application_lb_waf_enabled

**Expected behavior**
It should return the correct result.

**Additional context**

**Comment by bigdatasourav** [comment]
Depends on - https://github.com/turbot/steampipe-plugin-aws/issues/1157

**Comment by rajlearner17** [comment]
Released part of v0.2
